### ISSUE TITLE
Cross-cognate concept sets

### ISSUE THREAD

**Issue by chrzyki** [lexibank/wangbcd#3]
Hiya @MacyL and @LinguList,

we're issuing a warning for cross-concept cognate sets. Some make (semantically speaking) sense to me (e.g. ASH-DUST), others not so much (DIE-FOUR, DULL-TREE, WE-ANIMAL, etc.), but I'm by no means an expert for this kind of data. Is this worth investigating or is this 'just the way the data are'?

> WARNING wangbcd: Cross-concept cognate set 766
WARNING wangbcd: Cross-concept cognate set 855
WARNING wangbcd: Cross-concept cognate set 1235
WARNING wangbcd: Cross-concept cognate set 1234
WARNING wangbcd: Cross-concept cognate set 1009
WARNING wangbcd: Cross-concept cognate set 751
WARNING wangbcd: Cross-concept cognate set 1518
WARNING wangbcd: Cross-concept cognate set 164
WARNING wangbcd: Cross-concept cognate set 1232
WARNING wangbcd: Cross-concept cognate set 1548
WARNING wangbcd: Cross-concept cognate set 1550
WARNING wangbcd: Cross-concept cognate set 1552
WARNING wangbcd: Cross-concept cognate set 113
WARNING wangbcd: Cross-concept cognate set 1549
WARNING wangbcd: Cross-concept cognate set 1482
WARNING wangbcd: Cross-concept cognate set 1431
WARNING wangbcd: Cross-concept cognate set 1571
WARNING wangbcd: Cross-concept cognate set 1554

**Comment by xrotwang** [comment]
Allowing cross-concept cognacy is a **feature** of CLDF Wordlists. But since this is rarely used in datasets so far, we decided to add this warning. So what we'd need to make this fully functional is a way for the dataset to **declare** or opt-in to cross-concept cognacy -  and thereby making the warnings disappear.

**Comment by chrzyki** [comment]
Absolutely. Sorry, I didn't mean to sound like the data should be changed in a way to make the 'warnings go away', but in this particular case I was just curious about the particular cognate codings.

**Comment by xrotwang** [comment]
Ah, I see. I guess this dataset considers partial cognacy - which may result in strange-looking collections of concepts associated with a set of **words** which are related through cognacy of a single **morpeme** between them.

**Comment by chrzyki** [comment]
Gotcha, that makes sense. Thanks for taking the time to explain.

**Comment by xrotwang** [comment]
I still think we need a way for datasets to explicitly turn off these warnings.

**Comment by chrzyki** [comment]
I'll go ahead and create an issue for that.

**Comment by chrzyki** [comment]
You were faster. Thanks. :)

**Comment by LinguList** [comment]
The dataset was not meant as a cross-semantic cognate dataset. This means, the data is wrongly coded.

**Comment by LinguList** [comment]
I just checked: my own manual re-coding of the data, which should probably be used and has also been passed with the wordlist, is correct. So this should be used in the script for cognates then.

**Comment by xrotwang** [comment]
@LinguList so you mean replace https://github.com/lexibank/wangbcd/blob/b02882ff144c08e741c9d0225e6fd2b39aa54f88/lexibank_wangbcd.py#L44 ? Where is your coding to be found? And should we also add you as additional source for the cognacy judgements?

**Comment by LinguList** [comment]
The error is in the original data file that I provided, I just found out. The errors only occur for Old Chinese, which was separated in the original data. 

Wang's original data has a rather complex coding, which I already modified in a study where I used the data.

**Comment by LinguList** [comment]
Since it was easier to include this in lexibank, I used that derived data, but do not remember exactly why I did not include the original data.

**Comment by LinguList** [comment]
I am remembering now. The original data file was given to me in form of an excel spreadsheet. The data used here was converted from that spreadsheet to the lingpy-wordlist format. There are two IDs in the data: WANGID (reflecting the original cognate identifiers, which also reflect variants in morphology, and are thus difficult to interpret, e.g., 0a vs. 0b, although one could interpret them as partial cognates, yet since the data consists of Chinese characters, it is again hard to interpret those as slices, as we don't have a form). I added "normal" cogids for my analysis. These are in the column "COGID". They are all fine. But when comparing those with Old Chinese, there are errors. 

One could now do the following: add Wang's cogids in addition to the cogids that I have here. The difference: Old Chinese would be excluded, as there are no cognate IDs for old Chinese in form of the data I received.

**Comment by LinguList** [comment]
I think the current version of the data, as provided now, should have fixed this.

**Comment by LinguList** [comment]
Could you check, @chrzyki ?

**Comment by chrzyki** [comment]
> Could you check, @chrzyki ?

Looks good, thanks!

**Comment by xrotwang** [comment]
Well, the source List2015 needsto be added to make the tests pass. Are you taking over @chrzyki ?

**Comment by chrzyki** [comment]
Yes, already did that and regenerated the CLDF: https://buildbot.clld.org/#/builders/68/builds/7 & https://travis-ci.org/github/lexibank/wangbcd.

**Comment by LinguList** [comment]
The source just needs to be renamed, it is already there, right?

**Comment by chrzyki** [comment]
Yep, that is what I did given the source material & the title. Just renamed the source and regenerated the CLDF.
